apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubedeschedulers.operator.openshift.io
spec:
  group: operator.openshift.io
  names:
    kind: KubeDescheduler
    listKind: KubeDeschedulerList
    plural: kubedeschedulers
    singular: kubedescheduler
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: KubeDescheduler is the Schema for the deschedulers API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: spec holds user settable values for configuration
              type: object
              properties:
                deschedulingIntervalSeconds:
                  description: DeschedulingIntervalSeconds is the number of seconds between descheduler runs
                  type: integer
                  format: int32
                logLevel:
                  description: "logLevel is an intent based logging for an overall component.  It does not give fine grained control, but it is a simple way to manage coarse grained logging choices that operators have to interpret for their operands. \n Valid values are: \"Normal\", \"Debug\", \"Trace\", \"TraceAll\". Defaults to \"Normal\"."
                  type: string
                  default: Normal
                  enum:
                    - ""
                    - Normal
                    - Debug
                    - Trace
                    - TraceAll
                managementState:
                  description: managementState indicates whether and how the operator should manage the component
                  type: string
                  pattern: ^(Managed|Unmanaged|Force|Removed)$
                mode:
                  description: Mode configures the descheduler to either evict pods (Automatic) or to simulate the eviction (Predictive)
                  type: string
                  default: Predictive
                  enum:
                    - Automatic
                    - Predictive
                observedConfig:
                  description: observedConfig holds a sparse config that controller has observed from the cluster state.  It exists in spec because it is an input to the level for the operator
                  type: object
                  nullable: true
                  x-kubernetes-preserve-unknown-fields: true
                operatorLogLevel:
                  description: "operatorLogLevel is an intent based logging for the operator itself.  It does not give fine grained control, but it is a simple way to manage coarse grained logging choices that operators have to interpret for themselves. \n Valid values are: \"Normal\", \"Debug\", \"Trace\", \"TraceAll\". Defaults to \"Normal\"."
                  type: string
                  default: Normal
                  enum:
                    - ""
                    - Normal
                    - Debug
                    - Trace
                    - TraceAll
                profileCustomizations:
                  description: ProfileCustomizations contains various parameters for modifying the default behavior of certain profiles
                  type: object
                  properties:
                    devLowNodeUtilizationThresholds:
                      description: LowNodeUtilizationThresholds enumerates predefined experimental thresholds
                      type: string
                      default: Medium
                    namespaces:
                      description: Namespaces overrides included and excluded namespaces while keeping the default exclusion of all openshift-*, kube-system and hypershift namespaces
                      type: object
                      properties:
                        excluded:
                          type: array
                          items:
                            type: string
                        included:
                          type: array
                          items:
                            type: string
                    podLifetime:
                      description: PodLifetime is the length of time after which pods should be evicted This field should be used with profiles that enable the PodLifetime strategy, such as LifecycleAndUtilization
                      type: string
                      format: duration
                    thresholdPriority:
                      description: ThresholdPriority when set will reject eviction of any pod with priority equal or higher It is invalid to set it alongside ThresholdPriorityClassName
                      type: integer
                      format: int32
                    thresholdPriorityClassName:
                      description: ThresholdPriorityClassName when set will reject eviction of any pod with priority equal or higher It is invalid to set it alongside ThresholdPriority
                      type: string
                profiles:
                  description: Profiles sets which descheduler strategy profiles are enabled
                  type: array
                  items:
                    description: DeschedulerProfile allows configuring the enabled strategy profiles for the descheduler it allows multiple profiles to be enabled at once, which will have cumulative effects on the cluster.
                    type: string
                    enum:
                      - AffinityAndTaints
                      - TopologyAndDuplicates
                      - LifecycleAndUtilization
                      - DevPreviewLongLifecycle
                      - SoftTopologyAndDuplicates
                      - EvictPodsWithLocalStorage
                      - EvictPodsWithPVC
                unsupportedConfigOverrides:
                  description: 'unsupportedConfigOverrides holds a sparse config that will override any previously set options.  It only needs to be the fields to override it will end up overlaying in the following order: 1. hardcoded defaults 2. observedConfig 3. unsupportedConfigOverrides'
                  type: object
                  nullable: true
                  x-kubernetes-preserve-unknown-fields: true
            status:
              description: status holds observed values from the cluster. They may not be overridden.
              type: object
              properties:
                conditions:
                  description: conditions is a list of conditions and their status
                  type: array
                  items:
                    description: OperatorCondition is just the standard condition fields.
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                        format: date-time
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                generations:
                  description: generations are used to determine when an item needs to be reconciled or has changed in a way that needs a reaction.
                  type: array
                  items:
                    description: GenerationStatus keeps track of the generation for a given resource so that decisions about forced updates can be made.
                    type: object
                    properties:
                      group:
                        description: group is the group of the thing you're tracking
                        type: string
                      hash:
                        description: hash is an optional field set for resources without generation that are content sensitive like secrets and configmaps
                        type: string
                      lastGeneration:
                        description: lastGeneration is the last generation of the workload controller involved
                        type: integer
                        format: int64
                      name:
                        description: name is the name of the thing you're tracking
                        type: string
                      namespace:
                        description: namespace is where the thing you're tracking is
                        type: string
                      resource:
                        description: resource is the resource type of the thing you're tracking
                        type: string
                observedGeneration:
                  description: observedGeneration is the last generation change you've dealt with
                  type: integer
                  format: int64
                readyReplicas:
                  description: readyReplicas indicates how many replicas are ready and at the desired state
                  type: integer
                  format: int32
                version:
                  description: version is the level this availability applies to
                  type: string
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
