apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-descheduler-operand
rules:
- apiGroups:
  - "events.k8s.io"
  resources:
  - "events"
  verbs:
  - "get"
  - "watch"
  - "list"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "nodes"
  - "namespaces"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods/eviction"
  verbs:
  - "create"
- apiGroups:
  - "scheduling.k8s.io"
  resources:
  - "priorityclasses"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "create"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  resourceNames:
  - "descheduler"
  verbs:
  - "get"
  - "patch"
  - "delete"
