apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-descheduler-softtainter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-descheduler-softtainter
subjects:
  - kind: ServiceAccount
    name: openshift-descheduler-softtainter
    namespace: openshift-kube-descheduler-operator
